### ISSUE TITLE
problem to setup db with mysql

### ISSUE THREAD

**Issue by jbioman** [dparnell/nabaztag-php#1]
Hello,

i want to test your code, but i get problem with mysql.
first, your website seems well designed, and i congrats you for that.

i launch the setup, and all is ok.
i have a mysql server 5.5.24, running with wamp server.

once setup is done, i only see, in specified DB, a table called schema_migrations, with 2 rows :
001_create_database.sql and 002_create_apps_table.sql

this data seems not correct.

does you code support mysql db, or should i addapt the db table definition i can see in DB/migrate/ ?

shoudl'nt you add a test, once user is created by setup code, to check if value can be really read?

do you have a setup guide?may be i'll have found my answers if setup was ok, but how connect nabaztag to your serveur?
i just have to set "http://my-server-ip/nabaztag-php/" to my nabaztag settings?
may be you can add a requirement to a DB on your description?

please, help me.

a french user who want to help to improve your code ;-)

regards

**Comment by dparnell** [comment]
Hi,

  the code has not been tested with MySQL at all.  It currently uses the SQLite built in to PHP, however it should be possible to adapt the SQL migration system to cope with different databases.

Daniel

**Comment by jbioman** [comment]
i just create mysql tables and all seems ok.

user i well created after setup has ended, and i'm able to lg in.

but can you tell me how can i connect my rabbits to this server?
i did'nt find this out

thnaks

2012/7/1 Daniel Parnell <
reply@reply.github.com

**Comment by dparnell** [comment]
You need to put your rabbit into config mode.  To do this, unplug the rabbit then press the button on the top and apply the power.  When the lights turn blue (I think) let the button go.  You should then see a new wireless network with the MAC ID of your rabbit as part of the name.  You should then be able to connect your PC/Mac/Linux box to this new wireless network.  Look on the page and there should be an URL somewhere on the page ending in "/vl".  Change this to point to the IP address and path for your server.  For example I have "http://192.168.1.9/vl" in mine.

**Comment by jbioman** [comment]
thanks or your explanation.

my question was just about the url to set in the rabit.
where was this information about the url ending with vl?

anyway, i successfully set the url in my rabit, but it is not able to
connect.
the light on his noze is still flashing alternatively green /orange.
all 3 others light are orange.

if i set the url (the good one for mys config,of course), with no "vl" at
the end, the rabit connects well, all light are off, and the bottom is
violet.

so my question is :
what is this "vl"?
should it be a folder?a file?
is it an apache rewrite rule

should i just unzip your file from github, or should i add anithing else?

my serveur return a 404 error if i call http://192.168.1.35/nabazag-php/vl

can you help me?

thanks

2012/7/1 Daniel Parnell <
reply@reply.github.com

**Comment by dparnell** [comment]
The /vl is just the path to where your copy of the nabaztag-php site is being served.  I just chose /vl on my setup because it was similar to the official server.

**Comment by dparnell** [comment]
I'd be interested to see your changes to the database scripts.  Perhaps we can figure out some way to allow cross database migration scripts

**Comment by jbioman** [comment]
hello,

here is the sql code for create correct tables in mysql
i just create them in database, before execute the setp, on your website

CREATE TABLE IF NOT EXISTS `apps` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rabbit_id` int(11) NOT NULL,
  `next_update` int(11) NOT NULL,
  `reschedule_interval` int(11) NOT NULL,
  `application` varchar(64) NOT NULL,
  `data` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `rabbits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mac_id` varchar(32) NOT NULL,
  `name` varchar(128) NOT NULL,
  `owner_id` int(11) NOT NULL,
  `last_seen` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL,
  `is_admin` varchar(1) NOT NULL,
  `timezone_offset` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

2012/7/2 Daniel Parnell <
reply@reply.github.com

**Comment by jbioman** [comment]
ok,so i setup correctly my nabaztag, the bottom on the rabbit is violet, so
all seems ok for the rabbit,but on your website, i expect to see 1 rabbits
online, but it stays on 0
any idea?

thanks

2012/7/2 Daniel Parnell <
reply@reply.github.com

**Comment by dparnell** [comment]
Thanks for the create table statements.  I'll see what I can do about incorporating them into the code.
As for the site showing 0 rabbits online, when you log in does your rabbit appear on the list?  If so, are you able to configure any apps for it?

**Comment by jbioman** [comment]
ok, no problem for the table.
if i can help, don't hesitate to ask.

no, when i log in, my rabbit doesn't appear in the raddits list, and rabbit
list is empty
is there something in config that i have to check (apache, php)?

2012/7/2 Daniel Parnell <
reply@reply.github.com

**Comment by dparnell** [comment]
Have a look in the apache logs to see if there are any errors coming up.  It sounds like the rabbit is connecting successfully and getting the right firmware, but the database layer is not connecting properly when the rabbit hits the server.

**Comment by jbioman** [comment]
hello,

i find the problem.
in appache log, i saw lot of line with
[Sun Jul 08 10:56:42 2012] [error] [client 192.168.1.10] File does not
exist: C:/wamp/www/vl

so, despite my rabbit is configured to go on "192.168.1.35/nabaztag-php",
it seems he is always looking domainname/vl

anyway, i correct this, and now, i can see 1 rabbit connected.

but on the page f your website nammed "rabbits",
i don't see anything.

i only see "RabbitStatus" and nothing bellow.

i have an entry in DB in rabits tale, but nohing in apps

is it normal?
what should i see?

thanks

2012/7/3 Daniel Parnell <
reply@reply.github.com

**Comment by dparnell** [comment]
There wont be anything in the apps table until you configure an app using the web interface.
