### ISSUE TITLE
issue setting up db with sqlite

### ISSUE THREAD

**Issue by klreeher** [dparnell/nabaztag-php#2]
I'm attempting to set this up using the auto-configured SQLite database. However, whenever I do, I get the "Could not connect to database: - invalid data source name".

**Comment by dparnell** [comment]
I'm looking into this now.  The current code should get you past that error, but in the process it seems to have broken some other stuff

**Comment by dparnell** [comment]
This should now be fixed with the latest code :smile:

**Comment by klreeher** [comment]
Thanks, it's working now!

**Comment by dparnell** [comment]
Excellent :)  I hope your rabbit is happy now :rabbit:
